export const GET_ALL_POKEMON = "GET_ALL_POKEMON";
export const SET_ALL_POKEMON = "SET_ALL_POKEMON";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const SET_ALL_PRODUCT = "SET_ALL_PRODUCT";

export const POST_PRODUCT = "POST_PRODUCT";
export const SET_PRODUCT = "SET_PRODUCT";
